services:
  db-auth:
    image: postgres:15
    container_name: db-auth
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: auth
    volumes:
      - ./database/auth:/docker-entrypoint-initdb.d
    ports:
      - "5433:5432"
    networks:
      - app-network

  db-booking:
    image: postgres:15
    container_name: db-booking
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: booking
    volumes:
      - ./database/booking:/docker-entrypoint-initdb.d
    ports:
      - "5434:5432"
    networks:
      - app-network

  auth-go:
    build:
      context: ./auth/go-auth-service
    container_name: auth-go
    ports:
      - "8081:8081"
    depends_on:
      - db-auth
    networks:
      - app-network

  backend-java:
    build:
      context: ./backend/booking-service
    container_name: backend-java
    ports:
      - "8080:8080"
    depends_on:
      - db-booking
      - auth-go
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db-booking:5432/booking
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: pass
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend/coworking-app
    container_name: frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend-java
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
